// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWxCrfKf_BVeFoLZTuqdX0QDenRndy2w',
    appId: '1:209593547535:web:f2b1101ee8394478c6dc7a',
    messagingSenderId: '209593547535',
    projectId: 'rc-rtc-tolotanana',
    authDomain: 'rc-rtc-tolotanana.firebaseapp.com',
    databaseURL: 'https://rc-rtc-tolotanana-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rc-rtc-tolotanana.appspot.com',
    measurementId: 'G-66X26V6JHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB0UUtb4g4hCBmwmJE825-RDM9d8NPrjg',
    appId: '1:209593547535:android:76bc8211683e6056c6dc7a',
    messagingSenderId: '209593547535',
    projectId: 'rc-rtc-tolotanana',
    databaseURL: 'https://rc-rtc-tolotanana-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rc-rtc-tolotanana.appspot.com',
  );
}
